version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env  
    depends_on:
      - supabase
    command: npm start

  supabase:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: supabase
      POSTGRES_USER: supabase
      POSTGRES_DB: supabase

